### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCompletionsForSymbol' of null

### ISSUE THREAD

**Issue by DavidGiordana** [atom-haskell/autocomplete-haskell#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-haskell](https://github.com/atom-haskell/autocomplete-haskell) package, v0.4.3
### Stack Trace

Uncaught TypeError: Cannot read property 'getCompletionsForSymbol' of null

```
At /Users/david/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:95

TypeError: Cannot read property 'getCompletionsForSymbol' of null
    at SuggestionBuilder.module.exports.SuggestionBuilder.getSuggestions (/Users/david/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:153:53)
    at SuggestionBuilder.getSuggestions (/Users/david/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:3:61)
    at Object.getSuggestions (/Users/david/.atom/packages/autocomplete-haskell/lib/autocomplete-haskell.coffee:47:68)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
  2x -0:21.7.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:21 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:19.8.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -0:17 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter",
      "haskell-ghc-mod"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.4.3
autocomplete-python, v0.4.1
ide-haskell, v0.5.10
language-haskell, v1.0.0
linter-javac, v0.1.4

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
I've pushed 0.4.4, which will avoid this error. However, please install `haskell-ghc-mod`, since it is required for `autocomplete-haskell` to work.
