### ISSUE TITLE
Failed to load the autocomplete-haskell package

### ISSUE THREAD

**Issue by AlexMckey** [atom-haskell/autocomplete-haskell#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0-beta1
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-haskell](https://github.com/atom-haskell/autocomplete-haskell) package, v0.5.1
### Stack Trace

Failed to load the autocomplete-haskell package

```
At Cannot find module 'atom-backend-helper'

Error: Cannot find module 'atom-backend-helper'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Александр\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Александр\.atom\packages\autocomplete-haskell\lib\autocomplete-haskell.coffee:8:19)
    at Object.<anonymous> (C:\Users\Александр\.atom\packages\autocomplete-haskell\lib\autocomplete-haskell.coffee:80:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Александр\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.5.1
haskell-ghc-mod, v0.9.13
haskell-pointfree, v0.1.2
ide-haskell, v0.8.0
language-haskell, v1.4.11
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Please try uninstalling and reinstalling. Seems like some npm modules
failed to install properly.

2015-10-20 21:07 GMT+03:00 AlexMckey notifications@github.com:
